#!/bin/bash

# THE PUROPSE OF THIS FILE IS TO LOCATE AND COPY THE HEADER AND DEPENDENT
# LIBRARIES OF THE PLUGINS TO THEIR PROPER LOCATIONS

for dir in ${1}/*/; do
  # COPY PLUGIN DEPENDENT LIBRARIES
  cp ${dir}libs/* /usr/lib/chl/
  
  # COPY PLUGIN HEADER FILES
  cp ${dir}*.h /usr/include/chl/
done
