#!/bin/bash

# GET OS BIT TYPE
SYS_TYPE=$(uname -m)

# WHETHER TO COMPILE OR NOT
COMPILE=true

# FILE NAMES
DFILE="mysql.tar.gz"
DIR_NAME="mysql"
LIB_NAME="libmysqlclient.so"

# MYSQL C CONNECTOR DOWNLOAD URLS
MYSQL_64="https://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.6-linux-glibc2.5-x86_64.tar.gz"
MYSQL_32="https://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.6-linux-glibc2.5-i686.tar.gz"

echo "fetching MySQL C Connector..."
# DOWNLOAD MYSQL C CONNECTOR
if [ ${SYS_TYPE} == "x86_64" ]; then
  wget -q ${MYSQL_64} -O ${DFILE}
elif [[ ${SYS_TYPE,,} == *"arm"* ]]; then
  echo "ARM - no MYSQL support"
  COMPILE=false
else
  wget -q ${MYSQL_32} -O ${DFILE}
fi

if [ "${COMPILE}" = true ]; then
  echo "extracting files..."
  # EXTRACT FILES
  mkdir ${DIR_NAME}
  tar xf ${DFILE} -C ${DIR_NAME} --strip-components 1

  # MOVE LIBRARY
  mv $(readlink -f ${DIR_NAME}/lib/${LIB_NAME}) libs

  # COMPILE
  echo "Compiling..."
  gcc -std=c11 -c -Wall -Werror -fPIC src/*.c
  mv *.o ../../cmp

  echo "clean up..."
  # CLEAN UP
  rm -r ${DFILE} ${DIR_NAME}
fi

