#!/bin/bash

# GET OS BIT TYPE
SYS_TYPE=$(uname -m)

# FILE NAMES
DFILE="mysql.tar.gz"
DIR_NAME="mysql"
LIB_NAME="libmysqlclient.so"

# MYSQL C CONNECTOR DOWNLOAD URLS
MYSQL_64="https://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.6-linux-glibc2.5-x86_64.tar.gz"
MYSQL_32="https://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.6-linux-glibc2.5-i686.tar.gz"

echo "fetching MySQL C Connector..."
# DOWNLOAD MYSQL C CONNECTOR
if [ ${SYS_TYPE} == "x86_64" ]; then
  wget -q ${MYSQL_64} -O ${DFILE}
elif [ ${SYS_TYPE} == *"ARM"* ]; then
  echo "ARM - no MYSQL support, deleting files..."
  rm -r ../src/*
else
  wget -q ${MYSQL_32} -O ${DFILE}
fi

echo "extracting files..."
# EXTRACT FILES
mkdir ${DIR_NAME}
tar xf ${DFILE} -C ${DIR_NAME} --strip-components 1

# MOVE LIBRARY
mv $(readlink -f ${DIR_NAME}/lib/${LIB_NAME}) .

echo "clean up..."
# CLEAN UP
rm -r ${DFILE} ${DIR_NAME}
